# coding: utf-8

"""
    ProWritingAid API V2

    Official ProWritingAid API Version 2

    OpenAPI spec version: v2
    Contact: hello@prowritingaid.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AnalysisSummaryGraph(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'items': 'list[AnalysisSummaryGraphItem]'
    }

    attribute_map = {
        'name': 'Name',
        'items': 'Items'
    }

    def __init__(self, name=None, items=None):
        """
        AnalysisSummaryGraph - a model defined in Swagger
        """

        self._name = None
        self._items = None

        if name is not None:
          self.name = name
        if items is not None:
          self.items = items

    @property
    def name(self):
        """
        Gets the name of this AnalysisSummaryGraph.

        :return: The name of this AnalysisSummaryGraph.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this AnalysisSummaryGraph.

        :param name: The name of this AnalysisSummaryGraph.
        :type: str
        """

        self._name = name

    @property
    def items(self):
        """
        Gets the items of this AnalysisSummaryGraph.

        :return: The items of this AnalysisSummaryGraph.
        :rtype: list[AnalysisSummaryGraphItem]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this AnalysisSummaryGraph.

        :param items: The items of this AnalysisSummaryGraph.
        :type: list[AnalysisSummaryGraphItem]
        """

        self._items = items

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AnalysisSummaryGraph):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
