# coding: utf-8

"""
    ProWritingAid API V2

    Official ProWritingAid API Version 2

    OpenAPI spec version: v2
    Contact: hello@prowritingaid.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DocumentsRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_id': 'int',
        'name': 'str',
        'content': 'str',
        'content_type': 'str',
        'export_file_name': 'str'
    }

    attribute_map = {
        'document_id': 'DocumentId',
        'name': 'Name',
        'content': 'Content',
        'content_type': 'ContentType',
        'export_file_name': 'ExportFileName'
    }

    def __init__(self, document_id=None, name=None, content=None, content_type=None, export_file_name=None):
        """
        DocumentsRequest - a model defined in Swagger
        """

        self._document_id = None
        self._name = None
        self._content = None
        self._content_type = None
        self._export_file_name = None

        if document_id is not None:
          self.document_id = document_id
        if name is not None:
          self.name = name
        if content is not None:
          self.content = content
        if content_type is not None:
          self.content_type = content_type
        if export_file_name is not None:
          self.export_file_name = export_file_name

    @property
    def document_id(self):
        """
        Gets the document_id of this DocumentsRequest.

        :return: The document_id of this DocumentsRequest.
        :rtype: int
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id):
        """
        Sets the document_id of this DocumentsRequest.

        :param document_id: The document_id of this DocumentsRequest.
        :type: int
        """

        self._document_id = document_id

    @property
    def name(self):
        """
        Gets the name of this DocumentsRequest.

        :return: The name of this DocumentsRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this DocumentsRequest.

        :param name: The name of this DocumentsRequest.
        :type: str
        """

        self._name = name

    @property
    def content(self):
        """
        Gets the content of this DocumentsRequest.

        :return: The content of this DocumentsRequest.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """
        Sets the content of this DocumentsRequest.

        :param content: The content of this DocumentsRequest.
        :type: str
        """

        self._content = content

    @property
    def content_type(self):
        """
        Gets the content_type of this DocumentsRequest.

        :return: The content_type of this DocumentsRequest.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """
        Sets the content_type of this DocumentsRequest.

        :param content_type: The content_type of this DocumentsRequest.
        :type: str
        """

        self._content_type = content_type

    @property
    def export_file_name(self):
        """
        Gets the export_file_name of this DocumentsRequest.

        :return: The export_file_name of this DocumentsRequest.
        :rtype: str
        """
        return self._export_file_name

    @export_file_name.setter
    def export_file_name(self, export_file_name):
        """
        Sets the export_file_name of this DocumentsRequest.

        :param export_file_name: The export_file_name of this DocumentsRequest.
        :type: str
        """

        self._export_file_name = export_file_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DocumentsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
