# coding: utf-8

"""
    ProWritingAid API V2

    Official ProWritingAid API Version 2

    OpenAPI spec version: v2
    Contact: hello@prowritingaid.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class EntryMeaning(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'meaning': 'str',
        'part_of_speech': 'str',
        'synonyms': 'list[str]'
    }

    attribute_map = {
        'meaning': 'Meaning',
        'part_of_speech': 'PartOfSpeech',
        'synonyms': 'Synonyms'
    }

    def __init__(self, meaning=None, part_of_speech=None, synonyms=None):
        """
        EntryMeaning - a model defined in Swagger
        """

        self._meaning = None
        self._part_of_speech = None
        self._synonyms = None

        if meaning is not None:
          self.meaning = meaning
        if part_of_speech is not None:
          self.part_of_speech = part_of_speech
        if synonyms is not None:
          self.synonyms = synonyms

    @property
    def meaning(self):
        """
        Gets the meaning of this EntryMeaning.

        :return: The meaning of this EntryMeaning.
        :rtype: str
        """
        return self._meaning

    @meaning.setter
    def meaning(self, meaning):
        """
        Sets the meaning of this EntryMeaning.

        :param meaning: The meaning of this EntryMeaning.
        :type: str
        """

        self._meaning = meaning

    @property
    def part_of_speech(self):
        """
        Gets the part_of_speech of this EntryMeaning.

        :return: The part_of_speech of this EntryMeaning.
        :rtype: str
        """
        return self._part_of_speech

    @part_of_speech.setter
    def part_of_speech(self, part_of_speech):
        """
        Sets the part_of_speech of this EntryMeaning.

        :param part_of_speech: The part_of_speech of this EntryMeaning.
        :type: str
        """

        self._part_of_speech = part_of_speech

    @property
    def synonyms(self):
        """
        Gets the synonyms of this EntryMeaning.

        :return: The synonyms of this EntryMeaning.
        :rtype: list[str]
        """
        return self._synonyms

    @synonyms.setter
    def synonyms(self, synonyms):
        """
        Sets the synonyms of this EntryMeaning.

        :param synonyms: The synonyms of this EntryMeaning.
        :type: list[str]
        """

        self._synonyms = synonyms

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, EntryMeaning):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
