# coding: utf-8

"""
    ProWritingAid API V2

    Official ProWritingAid API Version 2

    OpenAPI spec version: v2
    Contact: hello@prowritingaid.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ThesaurusResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'word': 'str',
        'meanings': 'list[EntryMeaning]'
    }

    attribute_map = {
        'word': 'Word',
        'meanings': 'Meanings'
    }

    def __init__(self, word=None, meanings=None):
        """
        ThesaurusResponse - a model defined in Swagger
        """

        self._word = None
        self._meanings = None

        if word is not None:
          self.word = word
        if meanings is not None:
          self.meanings = meanings

    @property
    def word(self):
        """
        Gets the word of this ThesaurusResponse.
        The word that was searched

        :return: The word of this ThesaurusResponse.
        :rtype: str
        """
        return self._word

    @word.setter
    def word(self, word):
        """
        Sets the word of this ThesaurusResponse.
        The word that was searched

        :param word: The word of this ThesaurusResponse.
        :type: str
        """

        self._word = word

    @property
    def meanings(self):
        """
        Gets the meanings of this ThesaurusResponse.
        List of context-specific meanings

        :return: The meanings of this ThesaurusResponse.
        :rtype: list[EntryMeaning]
        """
        return self._meanings

    @meanings.setter
    def meanings(self, meanings):
        """
        Sets the meanings of this ThesaurusResponse.
        List of context-specific meanings

        :param meanings: The meanings of this ThesaurusResponse.
        :type: list[EntryMeaning]
        """

        self._meanings = meanings

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ThesaurusResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
